name: Unit Tests

on: [push]

jobs:

  unit:
    name: "Unit Tests"
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        npm install

    - name: Run Tests
      run: |
        lerna run test

    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        message: "https://github.com/openfl/openfl/actions\nNPM unit tests succeeded."

    - name: Notify Discord (failure)
      uses: appleboy/discord-action@master
      if: failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        message: "https://github.com/openfl/openfl/actions\nNPM unit tests failed."

