name: Unit Test

on: [push]

jobs:

  run-tests:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo apt-get install -y haxe

    - name: Install dependencies
      run: |
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib install mcover > /dev/null
        haxelib install hamcrest > /dev/null
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install hxp > /dev/null
        haxelib run hxp --install-hxp-alias

    - name: Install "openfl" command alias
      run: |
        haxelib dev openfl $GITHUB_WORKSPACE
        haxelib run openfl setup -alias -y

    - name: Run Unit Tests
      run: |
        hxp unit-test


