name: Unit Tests

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        haxelib install lime --quiet
        haxelib install utest --quiet
        haxelib install hxp --quiet
        haxelib run hxp --install-hxp-alias

    - name: Install "openfl" command alias
      run: |
        haxelib run openfl setup -alias -y

    - name: Run tests
      run: |
        hxp test

  notify:
    runs-on: ubuntu-16.04
    needs: [build]
    if: always()
    steps:
      - name: Notify Discord
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          include-details: 'false'
