name: Unit Test

on: [push]

jobs:

  haxelib:
    name: "Haxelib"
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install haxe -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        haxelib install mcover > /dev/null
        haxelib install hamcrest > /dev/null
        git clone https://github.com/openfl/munit $GITHUB_WORKSPACE/munit --depth 1
        haxelib dev munit $GITHUB_WORKSPACE/munit/src
        cd $GITHUB_WORKSPACE/munit/tool && haxe build.hxml
        haxelib install hxp > /dev/null
        haxelib run hxp --install-hxp-alias

    - name: Install "openfl" command alias
      run: |
        haxelib run openfl setup -alias -y

    - name: Run unit tests
      run: |
        hxp unit-test neko

    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#00C07F"
        username: "GitHub Bot"
        message: "Haxelib unit tests succeeded."
    
    - name: Notify Discord (success)
      uses: appleboy/discord-action@master
      if: failure()
      with:
        webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
        webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
        color: "#FF6562"
        username: "GitHub Bot"
        message: "Haxelib unit tests failed."
        
  npm:
    name: "NPM"
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup environment
      run: |
        sudo apt-get install -y --no-install-recommends wget
        wget --no-check-certificate -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        sudo h -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo add-apt-repository ppa:haxe/releases -y
        sudo apt-get update
        sudo apt-get install google-chrome-stable haxe npm -y
        mkdir $GITHUB_WORKSPACE/.haxelib
        haxelib setup $GITHUB_WORKSPACE/.haxelib
        haxelib dev openfl $GITHUB_WORKSPACE

    - name: Install dependencies
      run: |
        sudo npm install
        
    - name: Build openfl.js
      run: |
        npm run build

    - name: Run unit tests
      run: |
        npm run test
    
    - name: Notify Discord (success)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: "NPM unit tests succeeded."
      
    - name: Notify Discord (failure)
      if: failure()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: "NPM unit tests failed. (https://github.com/openfl/openfl/actions)"

